package com.evolgames.userinterface.control.windowcontrollers.gamewindowcontrollers;

public enum SettingsType {
    TOOL_SAVE_SETTINGS,
    POLYGON_CREATION_SETTINGS,
    IMAGE_SETTINGS,
    SCALE_IMAGE_SETTINGS,
    NONE,
    PIPE_SETTINGS,
    INSERT_POINT_SETTINGS,
    MOVE_POINT_SETTINGS,
    REMOVE_POINT_SETTINGS,
    MIRROR_SETTINGS,
    ROTATE_SETTINGS,
    SHIFT_SETTINGS,
    REVOLUTE_JOINT_SETTINGS,
    MOVE_JOINT_POINT_SETTINGS,
    DISTANCE_JOINT_SETTINGS,
    WELD_JOINT_SETTINGS,
    PRISMATIC_JOINT_SETTINGS,
    PROJECTILE_SETTINGS,
    MOVE_TOOL_POINT_SETTING,
    HAND_TOOL_POINT_SETTING,
    AMMO_TOOL_POINT_SETTING,
    ROTATE_IMAGE_SETTINGS, MOVE_IMAGE_SETTINGS, BOMB_TOOL_POINT_SETTING
}
